name: testy
on: workflow_dispatch
  inputs:
    mirror:
      description: 'Mirror build toggle'     
      required: true
      default: false
jobs:
  swagger:
    name: Swagger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'echo "field: ${{ github.event.inputs.foo }}"'
      - run: 'echo "payload: ${{ toJson(github.event.inputs) }}"'
      - run: echo baz
        if: github.event.action == 'baz'
      - run: cat README.md
